## Spectre

Pour [calculer]{.primary} / [tracer]{.secondary} le **spectre** d'un `AudioData` :

- Objet `SpectroData` construit à partir :
    - d'un `AudioData`
    - d'une `scipy.signal.ShortTimeFFT`

## Spectre {auto-animate="true" auto-animate-id="sd-value"}

```{.python code-line-numbers="1-2,5-10|3,12"}
from scipy.signal import ShortTimeFFT
from scipy.signal.windows import hamming
from OSmOSE.data.spectro_data import SpectroData

sft = ShortTimeFFT(
    win=hamming(1_024),
    hop=round(1_024*(1-0.8)), 
    fs=ad.sample_rate, 
    mfft=1_024
    )

sd = SpectroData.from_audio_data(data=ad, fft=sft)
```

::: {.fragment}

**=>** L'audio n'a **toujours pas** été manipulé.

:::

## Spectre {auto-animate="true" auto-animate-id="sd-value"}

```{.python code-line-numbers="14"}
from scipy.signal import ShortTimeFFT
from scipy.signal.windows import hamming
from OSmOSE.data.spectro_data import SpectroData

sft = ShortTimeFFT(
    win=hamming(1_024),
    hop=round(1_024*(1-0.8)), 
    fs=ad.sample_rate, 
    mfft=1_024
    )

sd = SpectroData.from_audio_data(data=ad, fft=sft)

sx = sd.get_value()
```

**=>** Les données sont toujours [récupérées]{.primary} / [traitées]{.secondary} **à la demande**.

## Spectre {auto-animate="true" auto-animate-id="sd-value"}

```{.python code-line-numbers="16"}
from scipy.signal import ShortTimeFFT
from scipy.signal.windows import hamming
from OSmOSE.data.spectro_data import SpectroData

sft = ShortTimeFFT(
    win=hamming(1_024),
    hop=round(1_024*(1-0.8)), 
    fs=ad.sample_rate, 
    mfft=1_024
    )

sd = SpectroData.from_audio_data(data=ad, fft=sft)

sx = sd.get_value()

sd.write(afs[0].path.parent / "npz")
```

**=>** Les **matrices** peuvent être écrites dans des fichiers `npz`

## Spectre {auto-animate="true" auto-animate-id="sd-value"}

```{.python code-line-numbers="1,3-6"}
from OSmOSE.data.spectro_file import SpectroFile

sf_1 = SpectroFile(
    Path(r"C:\Users\berthoga\Documents\Datasets\example_dataset\npz\2023_04_05_16_49_01.npz"),
    strptime_format = "%Y_%m_%d_%H_%M_%S"
    )
```

**=>** Ces fichiers `npz` peuvent être utilisés pour créer des **objets** `SpectroFile`

## Spectre {auto-animate="true" auto-animate-id="sd-value"}

```{.python code-line-numbers="1-6|7|9"}
ad2 = AudioData.from_files(
    files=afs, 
    begin=ad.end+Timedelta(seconds=1), 
    end=ad.end+Timedelta(seconds=1)+ad.duration
    )
ad2.sample_rate = ad.sample_rate
sd2 = SpectroData.from_audio_data(data=ad2, fft=sft)

sd2.write(afs[0].path.parent / "npz")
```

**=>** Les objets `SpectroData` peuvent être reconstruits à partir de plusieurs `SpectroFile` *(de la même manière que les `AudioData`)*

## Spectre {auto-animate="true" auto-animate-id="sd-value"}

```{.python code-line-numbers="1-4|6"}
sfs = [
    SpectroFile(f, strptime_format="%Y_%m_%d_%H_%M_%S") 
    for f in (afs[0].path.parent / "npz").glob("*.npz")
    ]

sd_tot = SpectroData.from_files(sfs)
```

**=>** Les objets `SpectroData` peuvent être reconstruits à partir de plusieurs `SpectroFile` *(de la même manière que les `AudioData`)*

## Spectrogramme {auto-animate="true" auto-animate-id="spectro"}

```{.python code-line-numbers="1,3-4"}
import matplotlib.pyplot as plt

sd.plot()
plt.show()
```

::: {.fragment}

**=>** Les **spectrogrammes** sont tracés sur la [figure par défaut]{.primary} de la version *legacy*.

:::

## Spectrogramme {auto-animate="true" auto-animate-id="spectro"}

```{.python code-line-numbers="1-2"}
fig, ax = plt.subplots(1,1)
sd.plot(ax=ax)

plt.show()
```

**=>** On peut spécifier un `Axes` sur lequel tracer le **spectrogramme**.

## Spectrogramme {auto-animate="true" auto-animate-id="spectro"}

```{.python code-line-numbers="1-7|9-11|12"}
ad2 = AudioData.from_files(
    files=afs, 
    begin=ad.end, 
    end=ad.end+ad.duration
    )
ad2.sample_rate = ad.sample_rate
sd2 = SpectroData.from_audio_data(data=ad2, fft=sft)

fig, axs = plt.subplots(2,1)
sd.plot(ax=axs[0])
sd2.plot(ax=axs[1])
plt.show()
```

**=>** Exemple pour **2 spectrogrammes** consécutifs sur **une même figure**.